@echo off
del /f /q /s *.bak
del /f /q /s *.dcu
del /f /q /s *.ddp
del /f /q /s *.~pas
del /f /q /s *.~dfm
del /f /q /s *.~ddp
del /f /q /s *.~dpr
del /f /q /s *.~dpk
del /f /q /s *.local
del /f /q /s *.identcache
del /f /q /s *.tvsconfig
del /f /q /s *.#0*
del /f /q /s *.il*
del /f /q /s *.map
del /f /q /s *.pch
del /f /q /s *.pdi
del /f /q /s *.tds
del /f /q /s *.obj
